### ISSUE TITLE
Nether Aura Nodes Create Signifigant Lag

### ISSUE THREAD

**Issue by ace5852** [Azanor/thaumcraft#1361]
Upon starting the server the tick time is normal, however upon entering and **leaving** the nether, a significant amount of is created. Running opis, I have found that aura nodes are causing an extremely high tick time. Included are 2 screenshots from Opis.

http://i.imgur.com/RGAkqYz.png
http://i.imgur.com/GIS2Bk5.png

I took at look at the aura node with the 1054 us tick time. It's a normal fading node. Doesn't seem to be anything special about it. 
http://i.imgur.com/9t9Rry8.png (The red box is caused by Opis, since I teleported to it with opis).

Thanks,
Ace

**Comment by tschallacka** [comment]
Uhm, not to be a nitpicker, but we are talking about 173 aura nodes, which cost a total time of 15 milliseconds... thats nothing compared to the data crunching they do. They all have tileentities that need to be stored, nbt data to be synced and written/read. 
The us tick time is 1/1000 of a millisecond. 
15ms for 173 nodes seems pretty decent to me. you can t even blink that fast.

The second picture seems to be the graphics rendering being displayed, but not sure because its cropped. this seems to be in order because nodes to take some calculations for the aspect colours every render, and they render always if loaded. The more aspects a node has, the more aspect points a node has the more fps lag.

The only feasable solution is have a  simple node rendering option in configuration where the size and colours arent calculated and nodes are always the same.
Its about a millisecond to half a millisecond per node for your graphics card to render if its rendering time you are displaying(or, get a better graphics card ;-))
so with 173 nodes loaded that would impact your graphics card a bit. my estimate with these numbers are you get about 10 fps, probaly lower because of mobs rendering.
But I must add.. 173 nodes is an awfull lot to have in one space.

How does your lag behave without goggles? is it the same?

**Comment by ace5852** [comment]
@tschallacka  Look more closely at the pictures. You'll find that one node is taking a whole 1 ms. This is the node in issue. This isn't impacted by the GPU in any way. The tick time is profiled on the server. My local GPU has no impact on this. For the record, the FPS is not impacted. It is the TPS on the server. And it's not in one space. It's spread out over all the loaded chunks on the server. 

Both pictures are tick time. The first is an overview showing all nodes grouped together. The second node is the individual tick times for each tile entity.

**Comment by Vaygrim** [comment]
Azanor is there news on this being fixed? I'm just curious why it was closed without update / comment.

**Comment by Azanor** [comment]
I closed it for a few reasons. Firstly I couldn't duplicate the problem myself, nor is there any code in nodes that make them act differently in the nether.
Since this seems to be an issue fairly unique to your server and I am redoing the entire node system for the next major update I thought I might as well close it.
I know that doesn't solve your problem, but have you considered simply breaking that node?
