### ISSUE TITLE
Blackscreen due to warp

### ISSUE THREAD

**Issue by Creysys** [Azanor/thaumcraft#1471]
So ive been ignoring warp for quite some time but i have to ask if its intended that my screen turns completely black for 3 minutes or so i also noticed my hunger drop

**Comment by MalkContent** [comment]
did you get the unnatural hunger debuff?

**Comment by Creysys** [comment]
i dont know what is happening everything turns black even the gui. dying or waiting long enough seems to fix it.

**Comment by MalkContent** [comment]
maybe a filter issue. try turning off thaumcrafts filters in the config

**Comment by Creysys** [comment]
okay i will try that thanks for your quick help

**Comment by MalkContent** [comment]
so, did it help?

**Comment by Creysys** [comment]
i will tell you once it happens again

**Comment by MalkContent** [comment]
you could try to give yourself a tc debuff with /effect :) you can find thaumcraft's potion id's in your game's log's startup sequence.

**Comment by Creysys** [comment]
the unnatural hunger effect is the cause i just tested it

it seems to be kinda broken i just removed optifine and it still exists

**Comment by MalkContent** [comment]
does this happen with i.e. sunscorched, too?

**Comment by Creysys** [comment]
disabling the filter/shader solves the issue there must be some kind of error or mistake in it

**Comment by Creysys** [comment]
im testing the other effects now

**Comment by MalkContent** [comment]
welp. drop list of mods like it was the thing you should have done in the first place :) maybe someone else stumbles in and you have a bad mod combo in common. since it's probably shader stuff, graphicscard and driver/opengl driver could also be interesting

**Comment by Creysys** [comment]
PotionUnnaturalHunger, PotionDeathGaze, PotionBlurredVision, PotionSunScorned are causing it

but it is related to my pc i suspect anti aliasing

**Comment by Creysys** [comment]
its not related to the mods i tested it with other clients of my modpack and it worked

it is related to my graphics card

**Comment by Creysys** [comment]
setting nvidia settings to default dont solve the issue as well

i guess i just disable thaumcraft shaders

to let you know i have a nvidia geforce gtx 750ti

**Comment by MalkContent** [comment]
:)

**Comment by MalkContent** [comment]
HA. I just recently added optifine to my mods /AND/ dabbled in aa using nvidia control panel. Ran into the exact same problem. After a little poking and prodding, it turned out to be in the vanilla options.txt. fboEnable has to be true, otherwise the shaders will cause a black screen.  
Pretty sure that, like me, you set it to false, because I wouldn't get AA to work otherwise. :/  
Probably nothing that can be done about it with configuring stuff, so it's a sophies choice between smooth edges and tasty shaders.

**Comment by Creysys** [comment]
Haha, that decision is made quite easily AA FTW :D

**Comment by MalkContent** [comment]
Well since you are running optifine and can control fullscreen resolution, you could try nvidia dsr instead of aa, though that's only for fullscreen :3 just recentrly tried that and worked nicely. On a side note, my 3 year old graphicscard just died. Might be a coincidence and a result of years of overclocking. *cough* just wanted to mention that as a fair warning.
