### ISSUE TITLE
Crash to Desktop Loop

### ISSUE THREAD

**Issue by itanshi** [Azanor/thaumcraft#1704]
This occurred on the Regrowth modpack version .7.1 which uses mod tweaker

This happens to people that are advanced in the modpack. I'm thinking they started thaumcraft. I cannot, myself say what steps there are to reproduce if any. It does not appear to be caused by a point of crash activity. This has occurred to many players (4 that I know of) and I had wanted to add it here for visibility. More crash reports may help solve this.

http://pastebin.com/LMV5HTmD initial crash
http://pastebin.com/Mfhnajqt crash I was killed during.

The crash logs mention something about Obelisks as I understand it.

Being killed in the moment I am trying to resolve the world (you connect prior to seeing the world usually) solves it as a workaround (for lack of a better word).

Thank you very much.

**Comment by thephoenixlodge** [comment]
The crashlogs don't mention obelisks. However if I'm interpreting it correctly it is the aspect generator failing to set the aspects of an item based on a crucible recipe. Since the one TC based recipe I add in that version is a crucible recipe for the obsidian totems I presumed that to be the issue.

**Comment by thephoenixlodge** [comment]
As stated on the related issue on my repository:
Have a feeling this is the culprit:
(from the new Witching Gadgets changelog)

added a NPE check for aspectlists on picture render

So this issue can be closed now
