### ISSUE TITLE
Feature Request: "Craftable" void node?

### ISSUE THREAD

**Issue by masonpinder** [Azanor/thaumcraft#1705]
Like transforming a void node into a tainted node by throwing taint into it, could you make some way to turn a node into a void node, by persay combining 9 nodes into some multiblock structure and it collides forming a black hole. Or something like throwing simply a primal charm, or one of each shard. OR making it become an infusion where you have to put a node in a jar in the middle and all the crystal clusters around it, PLUS a primal charm, PLUS some REALLY late game thaumcraft (possibly stuff after getting the stabilized node), 64 of EACH aspect and 256 of the primal aspects. Just to get a void node, and I say possibly make it a hard recipe just because of the possibilities of making the node become huge. Also, just an idea, make the node not be in a jar when it is finished, but rather be placed right below the top of the altar, so that it eats the entire infusion altar, just to make us people pay for dealing with such complicated magic!

Thank you very much for your consideration. I know this might be unreasonable to make, just I thought it would be helpful because I have spent at least two hours trying to find a hungry node to throw all my items in so that it is huge.

**Comment by MalkContent** [comment]
sorry, suggetsions/feature requests in the forum, please. otherwise issue tracker becomes swamped with them.
also my 2 cents: outright craftable hungry nodes would make creating irresponsibly big energized nodes seem like an obligation which everybody had to do to not feel like a halfassed thaumaturge. Seeing that it's basically just a big grind I don't think that would increase overall player experience. The fact that you really have to go on a downright journey to find gives it a much higher threshold plus people get to enjoy the travelling part in minecraft again. It's a good thing :3

**Comment by forsaken1111** [comment]
@MalkContent Couldn't agree more

**Comment by masonpinder** [comment]
@MalkContent I actually agree on that, with the thought of making it become a journey to find it. But I say there should at least be some type of device that points you in a general direction of one, if it is spawned. Or at least tells you if there are ANY in the world.

**Comment by MalkContent** [comment]
a minecraft world is absolutely gigantic. it is virtually impossible to not have any hungry nodes :) in my experience you have roughly 1 per 1k*1k horizontal blocks. in any case, please just close the issue and move the discussion to the forum
