### ISSUE TITLE
Wand enough capacitive

### ISSUE THREAD

**Issue by jejedu53** [Azanor/thaumcraft#1791]
Bonjour,

Le soucis est que même ayant le sceptre du vide qui donne 150 des différents vis et 64% de réduction de vis, nous ne pouvons pas créer de bâton primaire du vide coûtant  de chaque vis.

Hello,

The trouble is that even with the scepter of vacuum gives 150 different screws and screw 64% reduction, we can not create primary vacuum stick cost of each screw

http://zupimages.net/up/15/22/5365.png

**Comment by TheMadmanofChaos** [comment]
This, technically, not a bug. It has to due with how wand, staff, and wandcaps are registered in the code. While this has been reported many times, it is not a bug. You are going to need to settle with thaumium, and since it automatically regenerates up to ten percent of it's capacity and can't be used in crafting the slightly higher discount isn't strictly necessary.
