### ISSUE TITLE
DUPE

### ISSUE THREAD

**Issue by MrHelp** [Azanor/thaumcraft#1792]
http://www.youtube.com/watch?v=XyCcXqXwbMM

it is work now and on my server too!! Version Thaumcraft-1.7.10-4.2.3.5.jar

**Comment by T4ge** [comment]
This have been reported numerous times, and the issue is Cauldron, not
Thaumcraft.

**Comment by MrHelp** [comment]
it is not Cauldron. It is crucible

**Comment by TheMadmanofChaos** [comment]
You see, your on a server with a bit of software called "Cauldron", normally used for protection and anti-greifing plugins. The problem with this is that it makes base edits to MC code, and that causes incompatibility with some mobs, like what you have here with crucibles. Since neither cauldron, nor 1.7.10 TC builds are being supported this will not be fixed. But there is a work around, detailed here: #1699
