### ISSUE TITLE
Issues Loading Game

### ISSUE THREAD

**Issue by alexjvan** [Azanor/thaumcraft#1853]
I have issues loading my game whenever I put in the Thaumcraft Mod, I was wondering if you had any idea on how to fix this issue

Minecraft Crash Report: 
http://pastebin.com/zv7d8DtS

**Comment by igoutta** [comment]
Common' Al least try the last version. Go reck' youruself.

**Comment by alexjvan** [comment]
I tried that and I didn;t work, what version do you mean by last vesion? 4.2.3.4?

**Comment by GirafiStudios** [comment]
Geez. Learn to find latest versions for mods please..
http://minecraft.curseforge.com/mc-mods/223628-thaumcraft/files . Latest on there 4.2.3.5

**Comment by alexjvan** [comment]
I had 4.2.3.5 and it didn't work, no 4.2.3.- versions worked

**Comment by forsaken1111** [comment]
The error log you posted clearly says otherwise "        UCHIE   Thaumcraft{4.2.3.0} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.0.jar)"

They were commenting based upon that, thinking you had an old version. Nothing I see in that error log points to thaumcraft being the problem. Maybe another mod in your pack is conflicting somehow?
